# Generated by Django 5.1 on 2025-01-28 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_repairmaster_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pin_no', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repair_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='myapp.repairmaster')),
            ],
        ),
    ]
