# Generated by Django 5.1.1 on 2024-12-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cart_is_active_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_active_cart_per_user',
        ),
    ]
