# Generated by Django 5.1 on 2025-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_delivery_otp_order_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
